"""Initial database setup

Revision ID: c82a22de7bde
Revises: 
Create Date: 2025-12-06 22:53:42.215975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82a22de7bde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_type_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_types_id'), 'tournament_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('enter_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=True)
    op.create_table('football_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.Column('team_logo', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_football_teams_id'), 'football_teams', ['id'], unique=False)
    op.create_index(op.f('ix_football_teams_player_id'), 'football_teams', ['player_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('tournament_type_id', sa.Integer(), nullable=True),
    sa.Column('tournament_name', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_type_id'], ['tournament_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_player_id'), 'tournaments', ['player_id'], unique=False)
    op.create_index(op.f('ix_tournaments_tournament_type_id'), 'tournaments', ['tournament_type_id'], unique=False)
    op.create_table('football_teams_to_tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('football_team_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['football_team_id'], ['football_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_football_teams_to_tournaments_football_team_id'), 'football_teams_to_tournaments', ['football_team_id'], unique=False)
    op.create_index(op.f('ix_football_teams_to_tournaments_id'), 'football_teams_to_tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_football_teams_to_tournaments_tournament_id'), 'football_teams_to_tournaments', ['tournament_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('tour_number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('guest_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('guest_team_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_team_id'], ['football_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['football_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_guest_team_id'), 'matches', ['guest_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_guest_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_football_teams_to_tournaments_tournament_id'), table_name='football_teams_to_tournaments')
    op.drop_index(op.f('ix_football_teams_to_tournaments_id'), table_name='football_teams_to_tournaments')
    op.drop_index(op.f('ix_football_teams_to_tournaments_football_team_id'), table_name='football_teams_to_tournaments')
    op.drop_table('football_teams_to_tournaments')
    op.drop_index(op.f('ix_tournaments_tournament_type_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_player_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_football_teams_player_id'), table_name='football_teams')
    op.drop_index(op.f('ix_football_teams_id'), table_name='football_teams')
    op.drop_table('football_teams')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tournament_types_id'), table_name='tournament_types')
    op.drop_table('tournament_types')
    # ### end Alembic commands ###
